# Generated by Django 5.0.4 on 2024-04-30 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_gawgkawk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="gawGkAwk",
        ),
    ]
